### PR TITLE
support for SCRAM-SHA-256 authentication

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by lpil** [comment]
Is there a way to hide all these coverage annotations? It's pretty hard to read the code in places because of them

**Review by lpil — APPROVED** [review]
All looks very sensible to me, though I am unfamiliar with the protocol.

**Comment by tsloughter** [comment]
Oh yea, so tests pass on earlier version of postgres :(. Very confusing.

**Comment by tsloughter** [comment]
Something is screwy because now I also see:

```
Failure/Error: ?assertMatch(# { command := insert }, pgo : query ( "insert into hstore_tmp (id, labels) values ($1, $2)" , [ 1 , # { << "key-1" >> => << "value-1" >> , << "key-2" >> => << "value-2" >> } ] ))
  expected: = # { command := insert }
       got: {error,
                #{error => badarg_encoding,module => pg_types,
                  type_info =>
                      {type_info,16428,pg_array,[],default,
                          <<"_foo_ts_range">>,<<"array_send">>,
                          <<"array_recv">>,-1,<<"array_out">>,<<"array_in">>,
                          16429,
                          {type_info,16429,pg_record,[],default,
                              <<"foo_ts_range">>,<<"record_send">>,
                              <<"record_recv">>,-1,<<"record_out">>,
                              <<"record_in">>,0,undefined,0,
                              [23,3908],
                              [{type_info,23,pg_int4,[],default,<<"int4">>,
                                   <<"int4send">>,<<"int4recv">>,4,
                                   <<"int4out">>,<<"int4in">>,0,undefined,0,
                                   [],undefined},
                               {type_info,3908,pg_range,[],default,
                                   <<"tsrange">>,<<"range_send">>,
                                   <<"range_recv">>,-1,<<"range_out">>,
                                   <<"range_in">>,0,undefined,1114,[],
                                   undefined}]},
                          0,[],undefined},
                  value =>
                      #{<<"key-1">> => <<"value-1">>,
                        <<"key-2">> => <<"value-2">>}}}
      line: 358
```

And sometimes the timestamp tests pass with postgres 14. First guess is something is crashing but for some reason not showing up in the logs but results in configuration being lost on following tests that would explain the timestamp failures at least.

**Comment by benbro** [comment]
Not sure if it's relevant but fixing several silent or unhandled errors might help expose these kind of issues:
https://github.com/erleans/pgo/issues/57
https://github.com/erleans/pgo/issues/42
https://github.com/erleans/pgo/issues/41

**Comment by tsloughter** [comment]
@benbro very good point.

**Comment by tsloughter** [comment]
@benbro this might have worked!

I'm still finishing up the commits because I'm not positive how best to handle particular failures but I should have a PR open today or tomorrow.

**Comment by tsloughter** [comment]
Found a bug related to the socket death not being handled right by the connection process too. Hopefully will have that PR ready sometime today.

**Pull request merged**
