### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by lpil**
🚧

### CODE REVIEW

**Comment by tsloughter** [comment]
Could you make this take a general list of socket options like Postgrex does?

**Comment by lpil** [comment]
Yes certainly, though I've not managed to get this to work with this approach or the equivilent when passing a list of options. I've tested with an application that runs both PGO and Postgrex with the same configuration. Postgrex succeeds but PGO fails. I can't immediately see any difference between how they use `gen_tcp:connect` so I'm not sure what the issue might be.

**Comment by lpil** [comment]
@tsloughter How does this look now?

**Comment by lpil** [comment]
@tsloughter ping :)

**Comment by tsloughter** [comment]
Oh, sorry, I forgot this wasn't the issue but an PR that was ready to go :). Will get it merged. Thanks!

**Comment by tsloughter** [comment]
I'll merge it but weird the CI isn't running.

**Review by tsloughter — APPROVED** [review]

**Comment by lpil** [comment]
💜

**Pull request merged**
